@startuml asdf
scale 1.8
!define DARKBLUE
!includeurl https://raw.githubusercontent.com/Drakemor/RedDress-PlantUML/master/style.puml

class Subscriber <<interface>> {
  +update()
}

class ConcreteSubscriber {
  ...
}

class Publisher {
  -Subscriber[]
  +subscribe()
  +unsubscribe()
  +notifySubscribers()
}

Subscriber <|-- ConcreteSubscriber
Publisher o-- Subscriber


@enduml
